[alembic]
# migrations files kahan save hongi
script_location = alembic

# Note: database URL hum env.py mein .env se dynamically le rahe hain,
# isliye yahan sqlalchemy.url ki zaroorat nahi (env.py override karega)
sqlalchemy.url = postgresql://neondb_owner:npg_f1LhOK5kBEni@ep-curly-shape-at6yh9dm-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
